[Config]
MinimumVersion=26

[Distribution]
Distribution=debian
Release=trixie
Mirror=https://mirrors.aliyun.com

[Output]
Format=disk
ImageId=oneos
ImageVersion=0.0.5
OutputDirectory=mkosi.output
CompressOutput=no

[Content]
Bootable=yes
Bootloader=systemd-boot
Packages=
    linux-image-amd64
    systemd-boot-efi
    openssh-server
    bash
    ca-certificates
    curl
    less
    nano
    htop
    tree
    file
    lsof
    login
    procps
    psmisc
    util-linux
    kmod
    pciutils
    usbutils
    iproute2
    iputils-ping
    e2fsprogs
    dosfstools
    locales
    systemd-resolved
    dbus
    libpam-systemd
    cage
    foot
    labwc
    waybar
    fuzzel
    swaybg
    fonts-dejavu-core
    fonts-noto-cjk
    xkb-data
    libgl1-mesa-dri
WithDocs=no
Hostname=oneos
Locale=C.UTF-8
Timezone=Asia/Shanghai
RootShell=/bin/bash
Autologin=yes
KernelCommandLine=root=PARTUUID rw quiet vt.global_cursor_default=0

[Runtime]
Console=gui
KernelCommandLineExtra=video=1600x900
QemuArgs=-device virtio-keyboard-pci -device virtio-tablet-pci
